## 1. Importing NumPy

NumPy is imported using the conventional alias `np`.


In [1]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.0.2


## 2. Creating 1D, 2D, and 3D Arrays

NumPy arrays can represent data in different dimensions:
- **1D:** a sequence of values
- **2D:** rows and columns, similar to a table
- **3D:** multiple 2D arrays stacked together


In [2]:
# 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# 2D array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D array:")
print(array_1d)

print("\n2D array:")
print(array_2d)

print("\n3D array:")
print(array_3d)


1D array:
[10 20 30 40 50]

2D array:
[[1 2 3]
 [4 5 6]]

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 3. Checking Dimensions, Shape, Size, and Data Type

The `ndim`, `shape`, `size`, and `dtype` attributes provide useful information about an array.


In [3]:
for name, arr in [
    ("1D", array_1d),
    ("2D", array_2d),
    ("3D", array_3d)
]:
    print(f"{name} array:")
    print("  Dimensions (ndim):", arr.ndim)
    print("  Shape:", arr.shape)
    print("  Number of elements (size):", arr.size)
    print("  Data type (dtype):", arr.dtype)


1D array:
  Dimensions (ndim): 1
  Shape: (5,)
  Number of elements (size): 5
  Data type (dtype): int64
2D array:
  Dimensions (ndim): 2
  Shape: (2, 3)
  Number of elements (size): 6
  Data type (dtype): int64
3D array:
  Dimensions (ndim): 3
  Shape: (2, 2, 2)
  Number of elements (size): 8
  Data type (dtype): int64


## 4. Indexing and Slicing

NumPy uses zero-based indexing. Slicing allows a range of elements, rows, or columns to be selected.


In [4]:
print("1D first element:", array_1d[0])
print("1D last element:", array_1d[-1])
print("1D elements from index 1 to 3:", array_1d[1:4])

print("\n2D element at row 1, column 2:", array_2d[1, 2])
print("2D first row:", array_2d[0, :])
print("2D second column:", array_2d[:, 1])
print("2D first two columns:")
print(array_2d[:, :2])

print("\n3D first 2D block:")
print(array_3d[0])


1D first element: 10
1D last element: 50
1D elements from index 1 to 3: [20 30 40]

2D element at row 1, column 2: 6
2D first row: [1 2 3]
2D second column: [2 5]
2D first two columns:
[[1 2]
 [4 5]]

3D first 2D block:
[[1 2]
 [3 4]]


## 5. Reshaping Arrays

The `reshape()` function changes the shape of an array without changing its data. The total number of elements must remain the same.


In [5]:
numbers = np.arange(1, 13)

reshaped_2d = numbers.reshape(3, 4)
reshaped_3d = numbers.reshape(2, 2, 3)

print("Original 1D array:")
print(numbers)

print("\nReshaped to 3 x 4:")
print(reshaped_2d)

print("\nReshaped to 2 x 2 x 3:")
print(reshaped_3d)


Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2 x 2 x 3:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 6. Generating Arrays with NumPy Functions

NumPy provides convenient functions for creating arrays:
- `zeros()` creates arrays filled with zeros.
- `ones()` creates arrays filled with ones.
- `arange()` generates values over a specified interval.
- `linspace()` generates evenly spaced values between two endpoints.


In [6]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
arange_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 6)

print("zeros():")
print(zeros_array)

print("\nones():")
print(ones_array)

print("\narange(0, 10, 2):")
print(arange_array)

print("\nlinspace(0, 1, 6):")
print(linspace_array)


zeros():
[[0. 0. 0.]
 [0. 0. 0.]]

ones():
[[1. 1. 1.]
 [1. 1. 1.]]

arange(0, 10, 2):
[0 2 4 6 8]

linspace(0, 1, 6):
[0.  0.2 0.4 0.6 0.8 1. ]


## 7. Mathematical Operations

NumPy supports element-wise mathematical operations directly on arrays. This makes numerical calculations concise and efficient.


In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("b / a:", b / a)
print("a squared:", a ** 2)
print("Square root of a:", np.sqrt(a))


a + b: [ 6  8 10 12]
a - b: [-4 -4 -4 -4]
a * b: [ 5 12 21 32]
b / a: [5.         3.         2.33333333 2.        ]
a squared: [ 1  4  9 16]
Square root of a: [1.         1.41421356 1.73205081 2.        ]


## 8. Vectorized Operations

Vectorization allows an operation to be applied to an entire array without writing an explicit Python loop for each element.


In [8]:
marks = np.array([55, 68, 72, 81, 90])

# Add 5 bonus marks to every student
adjusted_marks = marks + 5

# Convert marks to percentages out of 100
percentage = marks / 100 * 100

print("Original marks:", marks)
print("After adding 5 bonus marks:", adjusted_marks)
print("Percentage values:", percentage)


Original marks: [55 68 72 81 90]
After adding 5 bonus marks: [60 73 77 86 95]
Percentage values: [55. 68. 72. 81. 90.]


## 9. Boolean Masking

Boolean masking selects elements that satisfy a condition. It is commonly used for filtering numerical datasets.


In [9]:
data = np.array([12, 25, 7, 30, 18, 42, 9, 35])

mask = data > 20
filtered_data = data[mask]

print("Original data:", data)
print("Boolean mask:", mask)
print("Values greater than 20:", filtered_data)

print("\nValues between 10 and 30:")
print(data[(data >= 10) & (data <= 30)])


Original data: [12 25  7 30 18 42  9 35]
Boolean mask: [False  True False  True False  True False  True]
Values greater than 20: [25 30 42 35]

Values between 10 and 30:
[12 25 30 18]


## 10. Broadcasting

Broadcasting allows NumPy to perform operations on arrays with compatible shapes without manually replicating values.


In [10]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

row_values = np.array([1, 2, 3])

result = matrix + row_values

print("Matrix:")
print(matrix)

print("\nValues broadcast across each row:")
print(row_values)

print("\nResult:")
print(result)


Matrix:
[[10 20 30]
 [40 50 60]]

Values broadcast across each row:
[1 2 3]

Result:
[[11 22 33]
 [41 52 63]]


## 11. Aggregate Functions

Aggregate functions summarize numerical data. Common functions include `sum()`, `mean()`, `min()`, `max()`, and `median()`.


In [11]:
scores = np.array([72, 85, 91, 68, 77, 95, 88])

print("Scores:", scores)
print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Median:", np.median(scores))


Scores: [72 85 91 68 77 95 88]
Sum: 576
Mean: 82.28571428571429
Minimum: 68
Maximum: 95
Median: 85.0


## 12. Aggregate Functions Along an Axis

For multidimensional arrays, aggregate functions can be applied across a particular axis.


In [12]:
sales = np.array([
    [120, 150, 130],
    [200, 180, 210],
    [160, 170, 155]
])

print("Sales data:")
print(sales)

print("\nSum of each column:", np.sum(sales, axis=0))
print("Mean of each column:", np.mean(sales, axis=0))
print("Minimum of each column:", np.min(sales, axis=0))
print("Maximum of each column:", np.max(sales, axis=0))
print("Median of each column:", np.median(sales, axis=0))


Sales data:
[[120 150 130]
 [200 180 210]
 [160 170 155]]

Sum of each column: [480 500 495]
Mean of each column: [160.         166.66666667 165.        ]
Minimum of each column: [120 150 130]
Maximum of each column: [200 180 210]
Median of each column: [160. 170. 155.]


## 13. Combined Numerical Analysis Example

The following example combines array creation, vectorized calculation, boolean masking, and aggregate functions to perform a small numerical analysis task.


In [13]:
daily_sales = np.array([120, 145, 98, 175, 210, 160, 190])

# Apply a 10% increase using vectorization
projected_sales = daily_sales * 1.10

# Select days with sales above the original average
above_average = projected_sales > projected_sales.mean()
high_sales_days = projected_sales[above_average]

print("Original daily sales:", daily_sales)
print("Projected sales after 10% increase:", projected_sales)
print("Projected average sales:", projected_sales.mean())
print("Projected sales above average:", high_sales_days)
print("Highest projected sales:", projected_sales.max())


Original daily sales: [120 145  98 175 210 160 190]
Projected sales after 10% increase: [132.  159.5 107.8 192.5 231.  176.  209. ]
Projected average sales: 172.54285714285717
Projected sales above average: [192.5 231.  176.  209. ]
Highest projected sales: 231.00000000000003
